### ISSUE TITLE
Device /dev/md2 excluded by a filter.

### ISSUE THREAD

**Issue by matwei** [mrlesmithjr/ansible-mdadm#19]
I tried to create a RAID1 partition for LVM on an partially configured system and got the error message above.

The playbook looks like this:

```
---
- name: Setup myserver
  hosts: myserver
  become: true
  vars:
    mdadm_arrays:
      - name: 'md2'
        devices:
          - '/dev/sda4'
          - '/dev/sdb4'
        filesystem: 'lvm'
        level: 1
        state: present
  roles:
    - role: mrlesmithjr.mdadm
```
At the console of the server I saw that there were partitions on the newly made /dev/md2:

```
# fdisk -l /dev/md2
Disk /dev/md2: 907.7 GiB, 973951991808 bytes, 1902249984 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x0008d9b9

Device     Boot     Start       End   Sectors  Size Id Type
/dev/md2p1           2048 139460607 139458560 66.5G 83 Linux
/dev/md2p2      139462654 142604287   3141634  1.5G  5 Extended
/dev/md2p5      139462656 142604287   3141632  1.5G 82 Linux swap / Solaris

Partition 2 does not start on physical sector boundary.
```
Using the advice given at https://www.simplstor.com/index.php/support/support-faqs/118-lvm-dev-excluded-by-filter I was able to create the physical volume with these commands:

```
# wipefs -a /dev/md2
# pvcreate /dev/md2
```

Now the playbook runs fine but the manual intervention contradicts the purpose of Ansible.
Can you tell me what happened here?
