### ISSUE TITLE
`update-initramfs -u` is missing

### ISSUE THREAD

**Issue by titarenko** [mrlesmithjr/ansible-mdadm#21]
**Describe the bug**

Seems like final step is missing: `update-initramfs -u`

```
# mdadm.conf
#
# !NB! Run update-initramfs -u after updating this file.
# !NB! This will ensure that initramfs has an uptodate copy.
```

**To Reproduce**

1. Buy server at [hetzner auction](https://www.hetzner.com/sb) (there will be no cost, since you can cancel server after experiment, that will not take too much time) with 2 disks without hardware raid
2. Ask to add another 2 drives
3. Use installimage (comment out 3rd and 4th disks to setup 2nd raid array after installation using this ansible role)
4. Use this role to build 2nd raid using following playbook
```
- hosts: all
  become: true
  vars:
    mdadm_arrays:
    - name: 'md3'
      devices:
        - '/dev/sdc'
        - '/dev/sdd'
      filesystem: 'ext4'
      level: '1'
      mountpoint: '/data'
      state: 'present'
      opts: 'noatime'
  roles:
    - role: mrlesmithjr.mdadm
  tasks:
```
5. Reboot server

**Expected behavior**
Server boots.

**Actual behavior**
Server doesn't boot.

**Desktop (please complete the following information):**
 - Target OS: Ubuntu 20.04
 - Version

```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:19:43) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.3
  libyaml = True
```

```
~/.ansible/roles/mrlesmithjr.mdadm/meta/.galaxy_install_info:version: v0.1.1
```
