### ISSUE TITLE
mdadm.conf entries do not use expected array name

### ISSUE THREAD

**Issue by jovial** [mrlesmithjr/ansible-mdadm#39]
**Describe the bug**

On Rocky 9, the mdadm.conf is being generated with lines similar to:

```
ARRAY /dev/md/cpt01:0 metadata=1.2 name=cpt01:0 UUID=1c22a1b7:83aea9e8:32ddbd4a:1ff7d63c
ARRAY /dev/md/localhost.localdomain:0 metadata=1.2 name=localhost.localdomain:0 
```

I am setting the name to be `md127` in mdadm_arrays. 

**To Reproduce**
- Run role against rocky 9 host
- Check /etc/mdadm.conf

**Expected behavior**

I would expect the config file to look more like:

```
ARRAY /dev/md/127 metadata=1.2 name=cpt01:0 UUID=1c22a1b7:83aea9e8:32ddbd4a:1ff7d63c
ARRAY /dev/md/localhost.localdomain:0 metadata=1.2 name=localhost.localdomain:0 
```

** Additional context **

There is some context in on in this issue in this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=606481#c1. In particular this comment:

```
For version 1.2 superblocks, the preferred way to create arrays is by using a name instead of a number.  For example, if the array is your home partition, then creating the array with the option --name=home will cause the array to be assembled with a random device number (which is what you are seeing now, when an array doesn't have an assigned number we start at 127 and count backwards), but there will be a symlink in /dev/md/ that points to whatever number was used to assemble the array.  The symlink in /dev/md/ will be whatever is in the name field of the superblock.  So in this example, you would have /dev/md/home that would point to /dev/md127 and the preferred method of use would be to access the device via the /dev/md/home entry.
```
I found that using the scan with the name set in the array generated it correctly:
```
- hosts: compute-regular-gen2
  gather_facts: false
  tasks:
    # Capture the raid array details to append to mdadm.conf
    # in order to persist between reboots
    - name: arrays | Capturing Array Details
      command: "mdadm --detail --scan /dev/{{ item.name }}"
      register: "array_details"
      changed_when: false
      with_items: "{{ mdadm_arrays }}"
      become: true
    
    - name: arrays | Updating /etc/mdadm.conf
      lineinfile:
        dest: /etc/mdadm.conf
        regexp: "^{{ item }}"
        line: "{{ item }}"
        state: "present"
      with_items: "{{ array_details.results | map(attribute='stdout_lines') | flatten }}"
      become: true
```
I think that needs work as essentially we want to match on the UUID to replace an existing entry, but putting it out there to solicit some feedback.
