### ISSUE TITLE
Support names that don't match md*

### ISSUE THREAD

**Issue by jovial** [mrlesmithjr/ansible-mdadm#40]
I'm wondering if we could support passing --name to `create`. Interested to here what you think and if we could do that in a backwards compatible way to support something like:

```
mdadm_arrays:
 - name: 'secondary'
   # Define disk devices to assign to array
   devices:
     - '/dev/sdb'
     - '/dev/sdc'
   # Define filesystem to partition array with
   filesystem: 'ext4'
   # Define the array raid level
   # 0|1|4|5|6|10
   level: '1'
   # Define mountpoint for array device
   mountpoint: '/mnt/md0'
   # Define if array should be present or absent
   state: 'present'
```

From reading: https://bugzilla.redhat.com/show_bug.cgi?id=606481#c1, this is seems to the recommend way to address a particular raid array.
